"""Added new fields to WeatherData

Revision ID: 17e30eab4059
Revises: 
Create Date: 2024-05-06 09:06:45.442687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "17e30eab4059"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_location",
        sa.Column("id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("source_location_pkey")),
    )
    op.create_index(
        op.f("source_location_id_idx"), "source_location", ["id"], unique=False
    )
    op.create_index(
        op.f("source_location_name_idx"), "source_location", ["name"], unique=False
    )
    op.create_table(
        "weather_data",
        sa.Column("id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("location_id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("temperature", mysql.FLOAT(), nullable=False),
        sa.Column("humidity", mysql.FLOAT(), nullable=False),
        sa.Column("wind_speed", mysql.FLOAT(), nullable=False),
        sa.Column("wind_direction", mysql.FLOAT(), nullable=False),
        sa.Column("rain_fall", mysql.FLOAT(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("latitude", mysql.FLOAT(), nullable=False),
        sa.Column("longitude", mysql.FLOAT(), nullable=False),
        sa.Column("cld", mysql.FLOAT(), nullable=False),
        sa.Column("pet", mysql.FLOAT(), nullable=False),
        sa.Column("tmn", mysql.FLOAT(), nullable=False),
        sa.Column("tmx", mysql.FLOAT(), nullable=False),
        sa.Column("wet", mysql.FLOAT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["source_location.id"],
            name=op.f("weather_data_location_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("weather_data_pkey")),
    )
    op.create_index(op.f("weather_data_id_idx"), "weather_data", ["id"], unique=False)

    import json

    with open("migrations/location_list.json", "r") as f:
        locations = json.load(f)
    for location in locations:
        op.execute(
            f"INSERT INTO source_location (name, is_active) VALUES ('{location}', {False})"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("weather_data_id_idx"), table_name="weather_data")
    op.drop_table("weather_data")
    op.drop_index(op.f("source_location_name_idx"), table_name="source_location")
    op.drop_index(op.f("source_location_id_idx"), table_name="source_location")
    op.drop_table("source_location")
    # ### end Alembic commands ###
